prefixes:
  ex: http://example.com/
  obo: http://purl.obolibrary.org/obo/
  edam: http://edamontology.org/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  xsd: http://www.w3.org/2001/XMLSchema#

mappings:
  individual:
    sources:
      - ['individualIDs-vs-age.csv~csv']
    #s: ex:$(StudySubjectID)
    s: ex:$(StudySubject)
    po:
      - [a, sio:SIO_000498] # a person
      - [sio:SIO_000008, ex:$(Age-Years)] # has attribute
      #- [sio:SIO_000008, ex:$(Age)] # has attribute
  age:
    source:
      - ['individualIDs-vs-age.csv~csv']
    s: ex:$(Age-Years)
    #s: ex:$(Age)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C25150]] # is about [Age]
      - [sio:SIO_000300, xsd:string] # has value string