---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  ordo: http://www.orpha.net/ORDO/
  this: "|||BASE|||"
sources:
  cde_patient_diagnosis-source:
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"
mappings:
  identifier_has_value_for_patientRole_diagnosis:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_patientRole_diagnosis:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis
        type: iri
  person_has_role_patientRole_diagnosis:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis
        type: iri
  patientRole_diagnosis_annotation:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: Diagnosis Patient
        datatype: xsd:string
  patientRole_diagnosis_realized_medical_diagnosis:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#medical_diagnosis
        type: iri
  medical_diagnosis_process_annotation:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)_process#medical_diagnosis
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/SIO_001001
        type: iri
    - predicates: rdfs:label
      objects:
        value: medical diagnosis
        datatype: xsd:string
  medical_diagnosis_process_annotation_start:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)_process#medical_diagnosis
    po:
    - predicates: http://semanticscience.org/resource/has-start-time
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#medical_diagnosis_startdate
        type: iri
  medical_diagnosis_process_annotation_start_value:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)_process#medical_diagnosis_startdate
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(date)"
        datatype: xsd:date
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/start-date
        type: iri
  longitudinal_information_gathering_process_diseaseX_has_part_medical_diagnosis:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_process#longitudinal_information_gathering_process_diseaseX
    po:
    - predicates: http://semanticscience.org/resource/has-part
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#medical_diagnosis
        type: iri
  medical_diagnosis_process_has_output:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)_process#medical_diagnosis
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_$(pid)_$(uniqid)#medical_diagnosis_Output
        type: iri
  medical_diagnosis_Output_annotation:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)#medical_diagnosis_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  medical_diagnosis_Output_type_annotation:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)#medical_diagnosis_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/SIO_001003
        type: iri
  medical_diagnosis_Output_type_label_annotation:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)#medical_diagnosis_Output
    po:
    - predicates: rdfs:label
      objects:
        value: "$(diagnostic_opinion)"
        datatype: xsd:string
  medical_diagnosis_Output_value_annotation:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)#medical_diagnosis_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(diagnostic_opinion)"
        datatype: xsd:string
  inout_from_medical_diagnosis_refers_to_concepts:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)#medical_diagnosis_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_$(pid)_$(uniqid)#medical_diagnosis_attribute_TypedAttributeNode
        type: iri
  has_attribute_of_inout_from_medical_diagnosis:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: http://semanticscience.org/resource/has-attribute
      objects:
        value: this:individual_$(pid)_$(uniqid)#medical_diagnosis_attribute_TypedAttributeNode
        type: iri
  inout_from_medical_diagnosis_refers_to_concept_medical_diagnosis_attribute_type:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)#medical_diagnosis_attribute_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/attribute
        type: iri
    - predicates: rdf:type
      objects:
        value: "$(ordo_uri)"
        type: iri
  inout_from_medical_diagnosis_refers_to_concept_medical_diagnosis_attribute_label:
    sources:
    - cde_patient_diagnosis-source
    s: this:individual_$(pid)_$(uniqid)#medical_diagnosis_attribute_TypedAttributeNode
    po:
    - predicates: rdfs:label
      objects:
        value: "$(diagnostic_opinion)"
        datatype: xsd:string
