---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  ordo: http://www.orpha.net/ORDO/
  this: "|||BASE|||"
sources:
  cde_patient_disease_progression-source:
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"
mappings:
  identifier_has_value_for_longitudinal_information_gathering_role:
    sources:
    - cde_patient_disease_progression-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_longitudinal_information_gathering_role:
    sources:
    - cde_patient_disease_progression-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_$(pid)_$(uniqid)#longitudinal_information_gathering_role
        type: iri
  person_has_role_longitudinal_information_gathering_role:
    sources:
    - cde_patient_disease_progression-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_$(pid)_$(uniqid)#longitudinal_information_gathering_role
        type: iri
  longitudinal_information_gathering_role_annotation:
    sources:
    - cde_patient_disease_progression-source
    s: this:individual_$(pid)_$(uniqid)#longitudinal_information_gathering_role
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: Patient for longitudinal information gathering
        datatype: xsd:string
  longitudinal_information_gathering_role_realized_longitudinal_information_gathering_process_diseaseX:
    sources:
    - cde_patient_disease_progression-source
    s: this:individual_$(pid)_$(uniqid)#longitudinal_information_gathering_role
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_process#longitudinal_information_gathering_process_diseaseX
        type: iri
  longitudinal_information_gathering_process_diseaseX_process_annotation:
    sources:
    - cde_patient_disease_progression-source
    s: this:individual_$(pid)_process#longitudinal_information_gathering_process_diseaseX
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/SIO_001052
        type: iri
    - predicates: rdfs:label
      objects:
        value: patient longitudinal data collection
        datatype: xsd:string
  1632390767535033_process_custom_annotation:
    sources:
    - cde_patient_disease_progression-source
    s: this:individual_$(pid)_$(uniqid)_process#longitudinal_information_gathering_process_diseaseX
    po:
    - predicates: sio:refers-to
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C17747
        type: iri
  1632390767535049_process_custom_annotation:
    sources:
    - cde_patient_disease_progression-source
    s: this:individual_$(pid)_$(uniqid)_process#longitudinal_information_gathering_process_diseaseX
    po:
    - predicates: rdfs:label
      objects:
        value: Longitudinal record of patient disease progression and events
        datatype: xsd:string
