---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  ordo: http://www.orpha.net/ORDO/
  this: "|||BASE|||"
sources:
  cde_patient_disease_history-source:
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"
mappings:
  identifier_has_value_for_patientRole_symptom_onset:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_patientRole_symptom_onset:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset
        type: iri
  person_has_role_patientRole_symptom_onset:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset
        type: iri
  patientRole_symptom_onset_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: Symptom Onset Patient
        datatype: xsd:string
  identifier_has_value_for_patientRole_diagnosis_date:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_patientRole_diagnosis_date:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date
        type: iri
  person_has_role_patientRole_diagnosis_date:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date
        type: iri
  patientRole_diagnosis_date_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: Diagnosis Date Patient
        datatype: xsd:string
  patientRole_symptom_onset_realized_patientRole_symptom_onset_process:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#patientRole_symptom_onset_process
        type: iri
  patientRole_symptom_onset_process_process_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)_process#patientRole_symptom_onset_process
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/SIO_001052
        type: iri
    - predicates: rdfs:label
      objects:
        value: data collection - symptom onset date recording process
        datatype: xsd:string
  patientRole_diagnosis_date_realized_patientRole_diagnosis_date_process:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#patientRole_diagnosis_date_process
        type: iri
  patientRole_diagnosis_date_process_process_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)_process#patientRole_diagnosis_date_process
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/SIO_001052
        type: iri
    - predicates: rdfs:label
      objects:
        value: data collection - diagnosis date recording process
        datatype: xsd:string
  longitudinal_information_gathering_process_has_part_patientRole_symptom_onset_process:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_process#longitudinal_information_gathering_process
    po:
    - predicates: http://semanticscience.org/resource/has-part
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#patientRole_symptom_onset_process
        type: iri
  longitudinal_information_gathering_process_has_part_patientRole_diagnosis_date_process:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_process#longitudinal_information_gathering_process
    po:
    - predicates: http://semanticscience.org/resource/has-part
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#patientRole_diagnosis_date_process
        type: iri
  patientRole_symptom_onset_process_process_has_output:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)_process#patientRole_symptom_onset_process
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset_process_Output
        type: iri
  patientRole_symptom_onset_process_Output_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset_process_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  patientRole_symptom_onset_process_Output_type_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset_process_Output
    po:
    - predicates: rdf:type
      objects:
        value: "$(onset_uri)"
        type: iri
  patientRole_symptom_onset_process_Output_type_label_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset_process_Output
    po:
    - predicates: rdfs:label
      objects:
        value: date of onset (in official CDE this is age of onset)
        datatype: xsd:string
  patientRole_symptom_onset_process_Output_value_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset_process_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(onset_date)"
        datatype: xsd:date
  patientRole_symptom_onset_process_output_annotation_timeinstant:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset_process_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(onset_date)"
        datatype: xsd:date
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/time-instant
        type: iri
  patientRole_diagnosis_date_process_process_has_output:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)_process#patientRole_diagnosis_date_process
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date_process_Output
        type: iri
  patientRole_diagnosis_date_process_Output_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date_process_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  patientRole_diagnosis_date_process_Output_type_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date_process_Output
    po:
    - predicates: rdf:type
      objects:
        value: "$(diagnosis_uri)"
        type: iri
  patientRole_diagnosis_date_process_Output_type_label_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date_process_Output
    po:
    - predicates: rdfs:label
      objects:
        value: "'age' at diagnosis"
        datatype: xsd:string
  patientRole_diagnosis_date_process_Output_value_annotation:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date_process_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(diagnosis_date)"
        datatype: xsd:date
  patientRole_diagnosis_date_process_output_annotation_timeinstant:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date_process_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(diagnosis_date)"
        datatype: xsd:date
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/time-instant
        type: iri
  inout_from_patientRole_symptom_onset_process_refers_to_concepts:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_symptom_onset_process_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_$(pid)_$(uniqid)#age_at_onset_TypedAttributeNode
        type: iri
  has_attribute_of_inout_from_patientRole_symptom_onset_process:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: http://semanticscience.org/resource/has-attribute
      objects:
        value: this:individual_$(pid)_$(uniqid)#age_at_onset_TypedAttributeNode
        type: iri
  inout_from_patientRole_symptom_onset_process_refers_to_concept_age_at_onset_type:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#age_at_onset_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/attribute
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/HP_0003674
        type: iri
  inout_from_patientRole_symptom_onset_process_refers_to_concept_age_at_onset_label:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#age_at_onset_TypedAttributeNode
    po:
    - predicates: rdfs:label
      objects:
        value: Stage/date of onset
        datatype: xsd:string
  inout_from_patientRole_diagnosis_date_process_refers_to_concepts:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_diagnosis_date_process_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_$(pid)_$(uniqid)#disagnosis_date_TypedAttributeNode
        type: iri
  has_attribute_of_inout_from_patientRole_diagnosis_date_process:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: http://semanticscience.org/resource/has-attribute
      objects:
        value: this:individual_$(pid)_$(uniqid)#disagnosis_date_TypedAttributeNode
        type: iri
  inout_from_patientRole_diagnosis_date_process_refers_to_concept_disagnosis_date_type:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#disagnosis_date_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/attribute
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C156420
        type: iri
  inout_from_patientRole_diagnosis_date_process_refers_to_concept_disagnosis_date_label:
    sources:
    - cde_patient_disease_history-source
    s: this:individual_$(pid)_$(uniqid)#disagnosis_date_TypedAttributeNode
    po:
    - predicates: rdfs:label
      objects:
        value: Stage/date of diagnosis
        datatype: xsd:string
