---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  ordo: http://www.orpha.net/ORDO/
  this: "|||BASE|||"
sources:
  cde_patient_care_pathway-source:
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"
mappings:
  identifier_has_value_for_patientRole_care_pathway_first_contact:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_patientRole_care_pathway_first_contact:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_care_pathway_first_contact
        type: iri
  person_has_role_patientRole_care_pathway_first_contact:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_care_pathway_first_contact
        type: iri
  patientRole_care_pathway_first_contact_annotation:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_care_pathway_first_contact
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: First Contact Patient
        datatype: xsd:string
  patientRole_care_pathway_first_contact_realized_patientRole_care_pathway_first_contact_process:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_care_pathway_first_contact
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#patientRole_care_pathway_first_contact_process
        type: iri
  patientRole_care_pathway_first_contact_process_process_annotation:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)_$(uniqid)_process#patientRole_care_pathway_first_contact_process
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C159705
        type: iri
    - predicates: rdfs:label
      objects:
        value: first contact with specialized center
        datatype: xsd:string
  patientRole_care_pathway_first_contact_process_process_annotation_start:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)_$(uniqid)_process#patientRole_care_pathway_first_contact_process
    po:
    - predicates: http://semanticscience.org/resource/has-start-time
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#patientRole_care_pathway_first_contact_process_startdate
        type: iri
  patientRole_care_pathway_first_contact_process_process_annotation_start_value:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)_$(uniqid)_process#patientRole_care_pathway_first_contact_process_startdate
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(first_contact_date)"
        datatype: xsd:date
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/start-date
        type: iri
  1632390761178519_process_custom_annotation:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)_$(uniqid)_process#patientRole_care_pathway_first_contact_process
    po:
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C16205
        type: iri
  longitudinal_information_gathering_process_diseaseX_has_part_patientRole_care_pathway_first_contact_process:
    sources:
    - cde_patient_care_pathway-source
    s: this:individual_$(pid)_process#longitudinal_information_gathering_process_diseaseX
    po:
    - predicates: http://semanticscience.org/resource/has-part
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#patientRole_care_pathway_first_contact_process
        type: iri
