prefixes:
  ex: http://example.com/
  obo: http://purl.obolibrary.org/obo/
  edam: http://edamontology.org/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  xsd: http://www.w3.org/2001/XMLSchema#


mappings:
  individual:
    sources:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    #s: ex:$(StudySubjectID)
    s: ex:$(StudySubject)
    po:
      - [a, sio:SIO_000498] # a person
      - [sio:SIO_000008, ex:$(Patient)] # has attribute
      - [sio:SIO_000008, ex:$(SymptomsConsistentwithCOVID-19)] # has attribute
      #- [sio:SIO_000008, ex:$(Symptoms Consistent with COVID-19)] # has attribute
      - [sio:SIO_000008, ex:$(COVID-19)] # has attribute
      - [sio:SIO_000008, ex:$(PatientStatus)] # has attribute
      #- [sio:SIO_000008, ex:$(Patient Status)] # has attribute
      - [sio:SIO_000008, ex:$(ICU)] # has attribute
      - [sio:SIO_000008, ex:$(StudyDOI)] # has attribute
      #- [sio:SIO_000008, ex:$(Study DOI)] # has attribute
      - [sio:SIO_000008, ex:$(Ethnicity)] # has attribute
      - [sio:SIO_000008, ex:$(BMI)] # has attribute
      - [sio:SIO_000008, ex:$(Smoking)] # has attribute
      - [sio:SIO_000008, ex:$(COVID-19DiseaseSeverityWHOOrdinalScale)] # has attribute
      #- [sio:SIO_000008, ex:$(COVID-19 Disease Severity (WHO Ordinal) Scale)] # has attribute
      - [sio:SIO_000008, ex:$(CharlsonComorbidityIndex)] # has attribute
      #- [sio:SIO_000008, ex:$(Charlson Comorbidity Index)] # has attribute
      - [sio:SIO_000008, ex:$(APACHEIIScore)] # has attribute
      #- [sio:SIO_000008, ex:$(APACHE II Score)] # has attribute
      - [sio:SIO_000008, ex:$(MechanicalVentilation)] # has attribute
      #- [sio:SIO_000008, ex:$(Mechanical Ventilation)] # has attribute
      - [sio:SIO_000008, ex:$(Asthma)] # has attribute
      - [sio:SIO_000008, ex:$(COPD)] # has attribute
      - [sio:SIO_000008, ex:$(DM)] # has attribute
      - [sio:SIO_000008, ex:$(CRP)] # has attribute
      #- [sio:SIO_000008, ex:$(CRP (mg/L))] # has attribute
      #- [sio:SIO_000008, ex:$(Ferritin(ng/mL))] # has attribute
      - [sio:SIO_000008, ex:$(Ferritin)] # has attribute
      - [sio:SIO_000008, ex:$(IL6)] # has attribute
  patient:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(Patient)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C16960]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string
  covid-19-symptoms:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    #s: ex:$(Symptoms Consistent with COVID-19)
    s: ex:$(SymptomsConsistentwithCOVID-19)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C173069]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string
  covid-19:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(COVID-19)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:MONDO_0100096]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string
  patient-status:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    #s: ex:$(Patient Status)
    s: ex:$(PatientStatus)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C166244]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string
  icu:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(ICU)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C53511]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string ## TODO boolean????
  study-doi:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    #s: ex:$(Study DOI)
    s: ex:$(StudyDOI)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [edam:data_1188]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/ URL????
  ethnicity:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(Ethnicity)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:GECKO_0000061]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string
  bmi:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(BMI)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:ExO_0000105]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/ float????
  smoking:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(Smoking)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C154329]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string
  covid-19-disease-severity-who-ordinal-scale:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    #s: ex:$(COVID-19 Disease Severity (WHO Ordinal) Scale)
    s: ex:$(COVID-19DiseaseSeverityWHOOrdinalScale)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C178899]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/integer????
  charlson-comorbidity-index:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    #s: ex:$(Charlson Comorbidity Index)
    s: ex:$(CharlsonComorbidityIndex)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C176422]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string
  apache-ii-score:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    #s: ex:$(APACHE II Score)
    s: ex:$(APACHEIIScore)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C121113]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string
  mechanical-ventilation:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    #s: ex:$(Mechanical Ventilation)
    s: ex:$(MechanicalVentilation)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C70909]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/boolean????
  asthma:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(Asthma)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C28397]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/boolean????
  copd:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(COPD)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:HP_0006510]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/boolean????
  dm:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(DM)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_2985]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/boolean????
  crp:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(CRP)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:000221, NCIT_C64572] # has unit mg/l
      - [sio:SIO_000332, [obo:NCIT_C64548]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/float????
  ferritin:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(Ferritin)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:000221, NCIT_C64572] # has unit mg/l == ng/ml
      - [sio:SIO_000332, [obo:NCIT_C74737]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/float????
  il6:
    source:
      - ['individualIDs-vs-phenotypic_features.csv~csv']
    s: ex:$(IL6)
    po:
      - [a, sio:SIO_000614] # a attribute
      - [sio:SIO_000332, [obo:NCIT_C74834]] # is about []
      - [sio:SIO_000300, xsd:string] # has value string/float????
