---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  ordo: http://www.orpha.net/ORDO/
  this: "|||BASE|||"
sources:
  cde_patient_consent-source:
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"
mappings:
  identifier_has_value_for_patientRole_consent:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_patientRole_consent:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_consent
        type: iri
  person_has_role_patientRole_consent:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_consent
        type: iri
  patientRole_consent_annotation:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_consent
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: Patient for status recording
        datatype: xsd:string
  patientRole_consent_realized_patient_consenting:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_consent
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#patient_consenting
        type: iri
  patient_consenting_process_annotation:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)_process#patient_consenting
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000810
        type: iri
    - predicates: rdfs:label
      objects:
        value: consenting process
        datatype: xsd:string
  patient_consenting_process_annotation_start:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)_process#patient_consenting
    po:
    - predicates: http://semanticscience.org/resource/has-start-time
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#patient_consenting_startdate
        type: iri
  patient_consenting_process_annotation_start_value:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)_process#patient_consenting_startdate
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(date)"
        datatype: xsd:date
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/start-date
        type: iri
  patient_consenting_has_input_consent_document:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)_process#patient_consenting
    po:
    - predicates: http://semanticscience.org/resource/has-input
      objects:
        value: this:individual_$(pid)_$(uniqid)#unidentifiedProcess_Output
        type: iri
  patient_consenting_has_input_consent_document_annotation:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#unidentifiedProcess_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/ICO_0000001
        type: iri
    - predicates: rdfs:label
      objects:
        value: information content entity
        datatype: xsd:string
  input_consent_document_has_value:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#unidentifiedProcess_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(url)"
        datatype: xsd:string
  patient_consenting_process_has_output:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)_process#patient_consenting
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_$(pid)_$(uniqid)#patient_consenting_Output
        type: iri
  patient_consenting_Output_annotation:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#patient_consenting_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  patient_consenting_Output_type_annotation:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#patient_consenting_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  patient_consenting_Output_type_label_annotation:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#patient_consenting_Output
    po:
    - predicates: rdfs:label
      objects:
        value: Patient Consent Record
        datatype: xsd:string
  patient_consenting_Output_value_annotation:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#patient_consenting_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(result_label)"
        datatype: xsd:string
  inout_from_patient_consenting_refers_to_concepts:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#patient_consenting_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_$(pid)_$(uniqid)#consent_attribute_TypedAttributeNode
        type: iri
  has_attribute_of_inout_from_patient_consenting:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: http://semanticscience.org/resource/has-attribute
      objects:
        value: this:individual_$(pid)_$(uniqid)#consent_attribute_TypedAttributeNode
        type: iri
  inout_from_patient_consenting_refers_to_concept_consent_attribute_type:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#consent_attribute_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/attribute
        type: iri
    - predicates: rdf:type
      objects:
        value: "$(result_uri)"
        type: iri
  inout_from_patient_consenting_refers_to_concept_consent_attribute_label:
    sources:
    - cde_patient_consent-source
    s: this:individual_$(pid)_$(uniqid)#consent_attribute_TypedAttributeNode
    po:
    - predicates: rdfs:label
      objects:
        value: "$(result_label)"
        datatype: xsd:string
