version: '3'

services:  
  # FAIR Data Point server    
  fdp:
    image: fairdata/fairdatapoint:1.12.0
    volumes:
      - ./fdp/application.yml:/fdp/application.yml:ro
    depends_on:
      - mongo
    networks:
      - default
      - bootstrap_graphdb_net    
        
  # FAIR Data Point client	
  fdp_client:
    image: fairdata/fairdatapoint-client:1.12.0
    hostname: fdp_client
    environment:
      FDP_HOST: fdp
    volumes:
      - ./fdp-client/variables.scss:/src/scss/custom/_variables.scss:ro
      - ./fdp-client/assets:/usr/share/nginx/html/assets:ro
      - ./fdp-client/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    depends_on:
      - fdp
    ports:
      - 8080:80
    networks:
      - default
      
  # Mongo for FDP server    
  mongo:
    image: mongo:4.2.3
    restart: always
    #ports:
    #  - 27017:27017
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - default
      
# Define networks here
networks:
  bootstrap_graphdb_net:
    external: true
