version: "3.6"
services:

  vnt6server:
    image: harbor2.vantage6.ai/infrastructure/server:cotopaxi
    ports:
      - 5000:5000
    volumes:
      - /opt/vantage6/config/server_config.yml:/mnt/config.yaml
      - /opt/vantage6/database:/mnt/database
    command: ["/bin/bash", "-c", "/vantage6/vantage6-server/server.sh"]

  vantage6-ui:
    image: harbor2.vantage6.ai/infrastructure/ui:cotopaxi
    ports:
      - 5988:80
    environment:
      - SERVER_URL=${SERVICE_URL}
#      - SERVER_URL=https://vantage6pro123.firstcoinpilots.src-pilot2.surf-hosted.nl
      - API_PATH=/api
