version: "3.6"
services:

  vnt6server:
    image: harbor2.vantage6.ai/infrastructure/server:cotopaxi
    ports:
      - 5000:5000
    volumes:
      - /opt/vantage6/config/server_config.yml:/mnt/config.yaml
      - /opt/vantage6/database:/mnt/database
    command: [ "uwsgi", "--http", ":5000", "--gevent", "1000", "--http-websockets", "--master", "--callable", "app", "--disable-logging", "--wsgi-file", "/vantage6/vantage6-server/vantage6/server/wsgi.py", "--pyargv", "/mnt/config.yaml"]

  vantage6-ui:
    image: harbor2.vantage6.ai/infrastructure/ui:cotopaxi
    ports:
      - 5988:80
    environment:
      - SERVER_URL=${SERVICE_URL}
      - API_PATH=/api