---
- name: Install and configure fdcube
  gather_facts: true
  hosts: localhost
  become: true

  tasks:

    - name: Create /rsc/plugins/fdcube/ folder
      ansible.builtin.file:
        path: /rsc/plugins/fdcube
        recurse: yes
        state: directory
        mode: '0700'

    - name: Create Nginx includes directory
      ansible.builtin.file:
        path: /etc/nginx/includes
        state: directory

    - name: Create ssl.conf file
      copy:
        content: |
          ssl_certificate /etc/letsencrypt/live/{{rsc_nginx_service_url}}/fullchain.pem; # managed by Certbot
          ssl_certificate_key /etc/letsencrypt/live/{{rsc_nginx_service_url}}/privkey.pem; # managed by Certbot
          include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
          ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        dest: /etc/nginx/includes/ssl.conf
        mode: 0644

    # - name: copy index_fdcube.html to /usr/share/nginx/html/index_fdcube.html
    #   copy:
    #     src: index_fdcube.html
    #     dest: /usr/share/nginx/html/index_fdcube.html
    #     mode: '0700'

    - name: copy index_fdcube.html to /usr/share/nginx/html/index_fdcube.html
      copy:
        dest: /usr/share/nginx/html/index_fdcube.html
        mode: 0644
        content: |
          <!DOCTYPE html>
          <html>
          <head>
          <title>Welcome to FD CUBE!</title>
          <style>
              body {
                  width: 35em;
                  margin: 0 auto;
                  font-family: Tahoma, Verdana, Arial, sans-serif;
                  }
          </style>
          </head>
          <body>
          <h1>Welcome to FD CUBE!</h1>
          <p>Go to:<br/>

          <a href="https://{{rsc_nginx_service_url}}:8000/">Vantage6</a>.<br/>
          <a href="https://{{rsc_nginx_service_url}}:8001/">Fair Data Point</a>.<br/>
          <a href="https://{{rsc_nginx_service_url}}:8002/">Graph DB</a>.<br/>

          </body>
          </html>

    - name: Add the location block to nginx
      script: init.sh

    - name: copy everything to /opt/fdcube
      command: cp -r ./{{ item }} /rsc/plugins/fdcube
      with_items:
        - "docker-compose.yml"
        - "bootstrap/"
        - "docs/"
        - "metadata/"
        - "others/"
        - "xomics-to-go/"

    - name: Run docker-compose
      command:
        cmd: docker compose up -d
        chdir: /rsc/plugins/fdcube/
